---
language: node_js
node_js:
- '0.8'
before_install:
- out/.travis/before_script.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- npm install
- bower install
after_success: out/.travis/after_success.sh
branches:
  only:
  - master
script: grunt
env:
  global:
  - REPO="git@github.com:angular-ui/ui-codemirror.git"